services:
  psql:
    image: postgres:latest
    container_name: psqlUsersStorage
    ports:
      - "5432:5432"
    networks:
      - pft_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pft
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
    - postgres_volume:/var/lib/postgresql/data
    
  users_manager:
    build:
      context: ./UsersManager
    container_name: user_service
    ports:
      - "6000:50051"
    networks:
      - pft_net
    depends_on:
      psql:
        condition: service_healthy

  apigateway:
    build:
      context: "./API-Gateway"
    container_name: api_gateway
    ports:
      - "8080:8080"
    networks:
      - pft_net
    volumes:
      - ./API-Gateway/log:/app/log

networks:
  pft_net:

volumes:
  postgres_volume:
  