name: Test for UsersManager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-usersmanager:
    name: Test UsersManager
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests in UsersManager
        run: |
          cd UsersManager
          go test -v ./...